error with gmail.

I just used hotmail instead.





smtplib.SMTPAuthenticationError
SMTPAuthenticationError: (534, '5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbvx\n5.7.14 OYJ8DGwC_tsknlcVAH4-LOd41EDxLtiZiLrI4rY_LK9kXWH4D1FAZB5O-z_7qKkHZ0aa-N\n5.7.14 iT6tNcqn3Mi_D9F3kgVbTOnP_cJSpgKRUcyk5ntlD6t3jTmIxJGWTpS9zPujKYXGySUaGA\n5.7.14 -eHnr1AtxmBihUsYSDZKvaO_MED_3fFKs2qBby28ilaT6BAEtXBWrS0YyB44GU-Oa4HhlY\n5.7.14 wrvnpRJ8X0z10E6XMgn8ejcZOy7Is> Please log in via your web browser and\n5.7.14 then try again.\n5.7.14  Learn more at\n5.7.14  https://support.google.com/mail/answer/78754 o15sm6819499igi.9 - gsmtp')

Traceback (most recent call last)
File "C:\p2\Python27\lib\site-packages\flask\app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "C:\p2\Python27\lib\site-packages\flask\app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "C:\p2\Python27\lib\site-packages\flask\app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\p2\Python27\lib\site-packages\flask\app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "C:\p2\Python27\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\p2\Python27\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\p2\Python27\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "C:\p2\Python27\lib\site-packages\flask\app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "C:\n\Dropbox\csd\VCS-git\flaskplay\111mail\112mail\fltg.py", line 77, in msendmail1
mail.send(msg)
File "C:\p2\Python27\lib\site-packages\flask_mail.py", line 491, in send
with self.connect() as connection:
File "C:\p2\Python27\lib\site-packages\flask_mail.py", line 144, in __enter__
self.host = self.configure_host()
File "C:\p2\Python27\lib\site-packages\flask_mail.py", line 165, in configure_host
host.login(self.mail.username, self.mail.password)
File "C:\p2\Python27\lib\smtplib.py", line 622, in login
raise SMTPAuthenticationError(code, resp)
SMTPAuthenticationError: (534, '5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbvx\n5.7.14 OYJ8DGwC_tsknlcVAH4-LOd41EDxLtiZiLrI4rY_LK9kXWH4D1FAZB5O-z_7qKkHZ0aa-N\n5.7.14 iT6tNcqn3Mi_D9F3kgVbTOnP_cJSpgKRUcyk5ntlD6t3jTmIxJGWTpS9zPujKYXGySUaGA\n5.7.14 -eHnr1AtxmBihUsYSDZKvaO_MED_3fFKs2qBby28ilaT6BAEtXBWrS0YyB44GU-Oa4HhlY\n5.7.14 wrvnpRJ8X0z10E6XMgn8ejcZOy7Is> Please log in via your web browser and\n5.7.14 then try again.\n5.7.14 Learn more at\n5.7.14 https://support.google.com/mail/answer/78754 o15sm6819499igi.9 - gsmtp')
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.


_____________


flask-mail smtplib.SMTPAuthenticationError SMTPAuthenticationError: support.google.com/mail/answer/78754
accounts.google.com/signin/continue
